version: "3.8"

services:
  mongo1:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongo-data-1:/data/db:rw
  mongo2:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - type: volume
        source: mongo-data-2
        target: /data/db
        read_only: false

volumes:
  mongo-data-1:
    name: mongo-data-1
  mongo-data-2:
    name: mongo-data-2
