version: "3.8"

services:
  mongo-example:
    image: mongo
    restart: always
    container_name: mongo-example
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - network_example

  mongo-express-example:
    image: mongo-express
    restart: always
    container_name: mongo-express-example
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-example:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo-example
    networks:
      - network_example

networks:
  network_example:
    name: network_example
    driver: bridge
