# version: '3.8'

services:
  mongo-example:
    container_name: mongo-example
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: fardi
      MONGO_INITDB_ROOT_PASSWORD: fardi

  mongo-express-example:
    container_name: mongo-express-example
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fardi
      ME_CONFIG_MONGODB_ADMINPASSWORD: fardi
      ME_CONFIG_MONGODB_URL: mongodb://fardi:fardi@mongo-example:27017/
      ME_CONFIG_BASICAUTH: false



