# version: '3.8'

services:
  nginx-example:
    container_name: nginx-example
    image: nginx:latest
    ports:
      - 8080:80
  mongo-example:
    container_name: mongo-example
    image: mongo:latest
    ports:
      - 27017:27017


